// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: isync.proto

package isync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportAgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId   string `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	AgentName string `protobuf:"bytes,2,opt,name=agentName,proto3" json:"agentName,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ReportAgentState) Reset() {
	*x = ReportAgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportAgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAgentState) ProtoMessage() {}

func (x *ReportAgentState) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAgentState.ProtoReflect.Descriptor instead.
func (*ReportAgentState) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{0}
}

func (x *ReportAgentState) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportAgentState) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *ReportAgentState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode string `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AgentStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *AgentStateRequest) Reset() {
	*x = AgentStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStateRequest) ProtoMessage() {}

func (x *AgentStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStateRequest.ProtoReflect.Descriptor instead.
func (*AgentStateRequest) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{2}
}

func (x *AgentStateRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type AgentStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentInfo []*ReportAgentState `protobuf:"bytes,1,rep,name=AgentInfo,proto3" json:"AgentInfo,omitempty"`
}

func (x *AgentStateResponse) Reset() {
	*x = AgentStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStateResponse) ProtoMessage() {}

func (x *AgentStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStateResponse.ProtoReflect.Descriptor instead.
func (*AgentStateResponse) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{3}
}

func (x *AgentStateResponse) GetAgentInfo() []*ReportAgentState {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

type AppHubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag  string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *AppHubRequest) Reset() {
	*x = AppHubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppHubRequest) ProtoMessage() {}

func (x *AppHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppHubRequest.ProtoReflect.Descriptor instead.
func (*AppHubRequest) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{4}
}

func (x *AppHubRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AppHubRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type AppHubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode string `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AppHubResponse) Reset() {
	*x = AppHubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppHubResponse) ProtoMessage() {}

func (x *AppHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppHubResponse.ProtoReflect.Descriptor instead.
func (*AppHubResponse) Descriptor() ([]byte, []int) {
	return file_isync_proto_rawDescGZIP(), []int{5}
}

func (x *AppHubResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *AppHubResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_isync_proto protoreflect.FileDescriptor

var file_isync_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69,
	0x73, 0x79, 0x6e, 0x63, 0x22, 0x62, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x25, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x4b, 0x0a,
	0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x09, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x35, 0x0a, 0x0d, 0x41, 0x70,
	0x70, 0x48, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x42, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x48, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x93, 0x02, 0x0a, 0x05, 0x49, 0x53, 0x79, 0x6e, 0x63, 0x12,
	0x40, 0x0a, 0x0e, 0x73, 0x79, 0x6e, 0x63, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0f, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x17, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x46, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x69,
	0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x73, 0x65, 0x6e,
	0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x41, 0x70, 0x70, 0x48, 0x75, 0x62, 0x12, 0x14, 0x2e, 0x69,
	0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x48, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x48, 0x75,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x73,
	0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x49, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x12, 0x0f,
	0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a,
	0x14, 0x2e, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x70, 0x70, 0x48, 0x75, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x68, 0x6f,
	0x6f, 0x6b, 0x2f, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x69, 0x73, 0x79, 0x6e, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_isync_proto_rawDescOnce sync.Once
	file_isync_proto_rawDescData = file_isync_proto_rawDesc
)

func file_isync_proto_rawDescGZIP() []byte {
	file_isync_proto_rawDescOnce.Do(func() {
		file_isync_proto_rawDescData = protoimpl.X.CompressGZIP(file_isync_proto_rawDescData)
	})
	return file_isync_proto_rawDescData
}

var file_isync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_isync_proto_goTypes = []interface{}{
	(*ReportAgentState)(nil),   // 0: isync.ReportAgentState
	(*Response)(nil),           // 1: isync.Response
	(*AgentStateRequest)(nil),  // 2: isync.AgentStateRequest
	(*AgentStateResponse)(nil), // 3: isync.AgentStateResponse
	(*AppHubRequest)(nil),      // 4: isync.AppHubRequest
	(*AppHubResponse)(nil),     // 5: isync.AppHubResponse
}
var file_isync_proto_depIdxs = []int32{
	0, // 0: isync.AgentStateResponse.AgentInfo:type_name -> isync.ReportAgentState
	1, // 1: isync.ISync.syncAgentState:input_type -> isync.Response
	2, // 2: isync.ISync.getAgentState:input_type -> isync.AgentStateRequest
	4, // 3: isync.ISync.sendMsgToAppHub:input_type -> isync.AppHubRequest
	1, // 4: isync.ISync.sendMsgToIthing:input_type -> isync.Response
	0, // 5: isync.ISync.syncAgentState:output_type -> isync.ReportAgentState
	3, // 6: isync.ISync.getAgentState:output_type -> isync.AgentStateResponse
	5, // 7: isync.ISync.sendMsgToAppHub:output_type -> isync.AppHubResponse
	4, // 8: isync.ISync.sendMsgToIthing:output_type -> isync.AppHubRequest
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_isync_proto_init() }
func file_isync_proto_init() {
	if File_isync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_isync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportAgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppHubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_isync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppHubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_isync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_isync_proto_goTypes,
		DependencyIndexes: file_isync_proto_depIdxs,
		MessageInfos:      file_isync_proto_msgTypes,
	}.Build()
	File_isync_proto = out.File
	file_isync_proto_rawDesc = nil
	file_isync_proto_goTypes = nil
	file_isync_proto_depIdxs = nil
}
